version: "3.3"

services:
  db:
    image: 'postgres:12'
    hostname: postgres
    container_name: auth_db_container
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DBNAME=postgres
    ports:
      - '5433:5432'
  
  web:
    build: .
    container_name: auth_container
    command: bash entrypoint.sh
    volumes:
      - .:/app
    ports:
      - 5001:5001
    depends_on:
      - db



volumes:
  postgres_data: